# Visit Okayama - Site Configuration
title: Visit Okayama
description: Discover the hidden gems of Japan's Sunny Country - A comprehensive guide to Okayama's culture, attractions, and local experiences
logo: /assets/img/logo.png
show_downloads: false
google_analytics: "UA-XXXXXXX-X" # Replace with your actual tracking ID
theme: "jekyll-theme-minimal"  # You can specify a theme here or remove this line if using a custom theme

# Site settings
author: Okayama Guide Team
email: contact@example.com
baseurl: "/okayama" # Adjust if your site is in a subdirectory
url: "https://username.github.io/okayama" # Your live site URL

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Navigation menu
navigation:
  - title: Home
    url: /
  - title: Destinations
    url: /destinations/
  - title: Experiences
    url: /experiences/
  - title: Local Food
    url: /food/
  - title: Trip Planning
    url: /planning/
  - title: About Us
    url: /about/
  - title: Contact
    url: /contact/
  - title: Events  # Example of an additional page
    url: /events/

# Collections
collections:
  destinations:
    output: true
    permalink: /destinations/:path/
  experiences:
    output: true
    permalink: /experiences/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: "destinations"
    values:
      layout: destination
  - scope:
      path: ""
      type: "experiences"
    values:
      layout: experience
